services:

  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow
    depends_on:
      - postgres
      - mysql
      - airflow_db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow_meta
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__WEBSERVER__RBAC: "True"

      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com

      # Email (optional)
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_USER}


      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}

      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data

    command: |
      bash -c "
      until airflow db check; do
        echo 'Waiting for database...'
        sleep 5
      done
      airflow db migrate
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
      airflow scheduler &
      exec airflow webserver
      "



  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: analytics

    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow_db:
    image: postgres:15
    container_name: airflow_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_meta
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# Access pgAdmin at http://localhost:5050
# Email:admin@local.com
# Password: admin


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
      MYSQL_DATABASE: stg_flight_prices
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: airflow
      PMA_PASSWORD: airflow
    ports:
      - "8081:80"
# Access phpMyAdmin at http://localhost:8081
# Server: mysql
# Username: airflow
# Password: airflow


volumes:
  postgres_data:
  mysql_data:
  pgadmin_data:
  airflow_db_data:
